# Generated by Django 4.0.4 on 2022-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'genre'), name='unique_book'),
        ),
        migrations.AddConstraint(
            model_name='cd',
            constraint=models.UniqueConstraint(fields=('genre_1', 'genre_2', 'music_list'), name='unique_cd'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('title', 'director', 'duration'), name='unique_movie'),
        ),
    ]
