# Generated by Django 4.0.4 on 2022-05-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_book_unique_book_cd_unique_cd_movie_unique_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_deposit',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='in_deposit',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='in_deposit',
        ),
    ]
