# Generated by Django 4.0.4 on 2022-05-28 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0003_remove_book_in_deposit_remove_cd_in_deposit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='can_be_deposited_by',
            new_name='deposit',
        ),
        migrations.AlterField(
            model_name='cd',
            name='can_be_deposited_by',
            field=models.ManyToManyField(blank=True, related_name='deposit', through='repository.Rent', to=settings.AUTH_USER_MODEL),
        ),
    ]
